from . import Birdsnap
from . import Caltech101
from . import CIFAR10
from . import CIFAR100
from . import CLEVERCounts
from . import Country211
from . import DescribableTextures
from . import EuroSAT
from . import FGVCAircraft
from . import Flowers102
from . import Food101
from . import GTSRB
from . import ImageNet
from . import ImageNet_CN
from . import Kinetics700
from . import KITTI
from . import MNIST
from . import OxfordPets
from . import PascalVOC2007
from . import PatchCamelyon
from . import SST2
from . import StanfordCars
from . import STL10
from . import SUN397
from . import UCF101