classes = [
    'Abyssinian',
    'Bengal',
    'Birman',
    'Bombay',
    'British Shorthair',
    'Egyptian Mau',
    'Maine Coon',
    'Persian',
    'Ragdoll',
    'Russian Blue',
    'Siamese',
    'Sphynx',
    'american bulldog',
    'american pit bull terrier',
    'basset hound',
    'beagle',
    'boxer',
    'chihuahua',
    'english cocker spaniel',
    'english setter',
    'german shorthaired',
    'great pyrenees',
    'havanese',
    'japanese chin',
    'keeshond',
    'leonberger',
    'miniature pinscher',
    'newfoundland',
    'pomeranian',
    'pug',
    'saint bernard',
    'samoyed',
    'scottish terrier',
    'shiba inu',
    'staffordshire bull terrier',
    'wheaten terrier',
    'yorkshire terrier',
]

templates = [
    'a photo of a {}, a type of pet.',
]